interface Insides {
	name: string;
	prodi: string;
	semester: number;
	img: string;
}

type Panitias = Record<string, Insides[]>;

export const panitias: Panitias = {
	ketua: [
		{
			name: "Muhammad Usama Hendra",
			prodi: "K3",
			semester: 5,
			img: "usamahendra",
		},
		{ name: "Satya Rizkiano", prodi: "HI", semester: 5, img: "satya_rizkiano" },
		{ name: "Fauzi Syahrul", prodi: "IQT", semester: 5, img: "fauzi_syahrul" },
	],
	sekretaris: [
		{
			name: "Abinaya Azhar Probo Kusumo",
			prodi: "TI",
			semester: 5,
			img: "abinaya_azhar",
		},
		{ name: "Wegig", prodi: "K3", semester: 5, img: "wegig" },
		{
			name: "Jihad Khoiruddin",
			prodi: "MNJ",
			semester: 5,
			img: "jihad_khoiruddin",
		},
		{ name: "Zaki Kusnadi", prodi: "K3", semester: 5, img: "zaki_kusnadi" },
		{ name: "Akmal Fauzi", prodi: "MNJ", semester: 5, img: "akmal_fauzi" },
	],
	bendahara: [
		{ name: "Ridho Ilham", prodi: "AGRO", semester: 5, img: "ridho_ilham" },
		{ name: "Aldhino", prodi: "MNJ", semester: 5, img: "aldhino" },
		{ name: "Rafie", prodi: "MNJ", semester: 5, img: "rafie" },
		{ name: "Salim Musyafa", prodi: "HI", semester: 5, img: "salim_musyafa" },
	],
	keamanan: [
		{ name: "Nazih Sukma", prodi: "HI", semester: 5, img: "nazih_sukma" },
		{ name: "Sidiq", prodi: "PBA", semester: 5, img: "sidiq" },
		{
			name: "Fauzan Hibaturrahman",
			prodi: "K3",
			semester: 5,
			img: "fauzan_hibaturrahman",
		},
		{ name: "Zaki Su'aidi", prodi: "EI", semester: 5, img: "zaki_suaidi" },
		{ name: "Ilham Ramadhan", prodi: "K3", semester: 5, img: "ilham_ramadhan" },
		{ name: "Arifa Bintang", prodi: "IQT", semester: 5, img: "arifa_bintang" },
		{ name: "Firmannuril", prodi: "SAA", semester: 5, img: "firmannuril" },
		{
			name: "Andhika Dzakwan",
			prodi: "MNJ",
			semester: 5,
			img: "andhika_dzakwan",
		},
		{ name: "Nandhika", prodi: "HI", semester: 5, img: "nandhika" },
		{ name: "Hanif", prodi: "PBA", semester: 5, img: "hanif" },
		{ name: "Naufal Dzaki", prodi: "HI", semester: 5, img: "naufal_dzaki" },
		{ name: "Dimitri Ulung", prodi: "EI", semester: 5, img: "dimitri_ulung" },
		{
			name: "Shulthan Maulana Zuhdi",
			prodi: "K3",
			semester: 5,
			img: "shulthan_maulana",
		},
		{
			name: "Brilliant Daffa",
			prodi: "K3",
			semester: 5,
			img: "brilliant_daffa",
		},
		{
			name: "Aditya Al aziz",
			prodi: "PAI",
			semester: 3,
			img: "aditya_al_aziz",
		},
	],
	designer: [
		{ name: "Rio Riyadi", prodi: "Ilkom", semester: 5, img: "rio_riyadi" },
		{ name: "Samsu Yusa", prodi: "Ilkom", semester: 5, img: "samsu_yusa" },
		{
			name: "Edwin Fadhillah Putra",
			prodi: "TI",
			semester: 5,
			img: "edwin_fadhillah",
		},
		{
			name: "Raffa Erfansyah",
			prodi: "Ilkom",
			semester: 5,
			img: "raffeerfansyah",
		},
		{ name: "Haydar", prodi: "HI", semester: 5, img: "haydar" },
		{ name: "Alif Huda", prodi: "TI", semester: 5, img: "alif_huda" },
		{
			name: "Sultan Al Kahfi",
			prodi: "MNJ",
			semester: 5,
			img: "sultan_al_kahfi",
		},
		{
			name: "Brucad Almagribi",
			prodi: "TI",
			semester: 5,
			img: "brucad_almagribi",
		},
		{
			name: "Mustaqim Nawahhudi",
			prodi: "TI",
			semester: 5,
			img: "mustaqim_nawahudi",
		},
		{
			name: "Haedar Rafif Surya Negara",
			prodi: "Ilkom",
			semester: 3,
			img: "haedar_rafif",
		},
	],
	dokumentasi: [
		{ name: "Dzil Izzat", prodi: "TBI", semester: 5, img: "dzil_izzat" },
		{ name: "Aldhyto Hasan", prodi: "MNJ", semester: 5, img: "aldhyto_hasan" },
		{ name: "Aqila Zain", prodi: "K3", semester: 5, img: "aqila_zain" },
		{ name: "Amran Syarif", prodi: "K3", semester: 5, img: "amran_syarif" },
		{ name: "Najib Ramadhan", prodi: "K3", semester: 5, img: "najib_ramadhan" },
		{
			name: "Almiftahul Riski",
			prodi: "Ilkom",
			semester: 5,
			img: "almiftahul_riski",
		},
		{ name: "Althof Faizan", prodi: "HI", semester: 5, img: "althof_faizan" },
		{
			name: "Reyhan Iskandar",
			prodi: "TI",
			semester: 3,
			img: "reyhan_iskandar",
		},
	],
	acara: [
		{
			name: "Arrayan Fikri",
			prodi: "Ilkom",
			semester: 5,
			img: "arrayan_fikri",
		},
		{
			name: "Muhammad Naufal",
			prodi: "MNJ",
			semester: 5,
			img: "muhammad_naufal",
		},
		{ name: "Dzaki Zidan", prodi: "MNJ", semester: 5, img: "dzaki_zidan" },
		{
			name: "Fadhilmu'tasimbillah",
			prodi: "K3",
			semester: 5,
			img: "fadhilmutasimbillah",
		},
		{ name: "Sun Fauzi", prodi: "MNJ", semester: 5, img: "sun_fauzi" },
		{
			name: "Ahnaf Athaullah",
			prodi: "K3",
			semester: 5,
			img: "ahnaf_athaullah",
		},
		{ name: "Alfredo Rizky", prodi: "MNJ", semester: 5, img: "alfredo_rizky" },
		{ name: "Rafi Hanief", prodi: "MNJ", semester: 5, img: "rafi_hanief" },
		{
			name: "Ghifari Alhafiz",
			prodi: "Ilkom",
			semester: 5,
			img: "ghifari_alhafiz",
		},
		{
			name: "Fauzi Hartanto",
			prodi: "Ilkom",
			semester: 5,
			img: "fauzi_hartanto",
		},
		{ name: "Muhammad Rafi", prodi: "MNJ", semester: 5, img: "muhammad_rafi" },
		{ name: "Halim", prodi: "Ilkom", semester: 3, img: "halim" },
	],
	kerohanian: [
		{
			name: "Taufiqnurrahman",
			prodi: "MNJ",
			semester: 5,
			img: "taufiqnurrahman",
		},
		{
			name: "Taufiqie Anindia",
			prodi: "MNJ",
			semester: 5,
			img: "taufiqie_anindia",
		},
		{
			name: "Muhammad Aditya Azka",
			prodi: "TI",
			semester: 5,
			img: "muhammad_aditya",
		},
		{ name: "Ghatan Alif", prodi: "IQT", semester: 5, img: "ghatan_alif" },
		{ name: "Irfan Anshori", prodi: "PAI", semester: 5, img: "irfan_anshori" },
		{ name: "Kemal Mayitra", prodi: "HI", semester: 5, img: "kemal_mayitra" },
		{ name: "Azmi Rabbani", prodi: "IQT", semester: 5, img: "azmi_rabbani" },
		{ name: "Hafiz Imron", prodi: "HES", semester: 5, img: "hafiz_imron" },
	],
	keolahragaan: [
		{
			name: "Riski Arrasyid",
			prodi: "MNJ",
			semester: 5,
			img: "riski_arrasyid",
		},
		{ name: "Agus Faisal", prodi: "PBA", semester: 5, img: "agus_faisal" },
		{
			name: "Zaki Fadhlurrahman",
			prodi: "Ilkom",
			semester: 5,
			img: "zaki_fadhlurrahman",
		},
		{ name: "Hafizullah", prodi: "HI", semester: 5, img: "hafizullah" },
		{
			name: "Ahmad Rafid Nuafal",
			prodi: "HI",
			semester: 5,
			img: "ahmad_rafid",
		},
		{
			name: "Agung Abdullah",
			prodi: "PMH",
			semester: 5,
			img: "agung_abdullah",
		},
		{ name: "Ari Dwi", prodi: "AGRO", semester: 5, img: "ari_dwi" },
		{ name: "Keysfil Harir", prodi: "K3", semester: 5, img: "keysfil_harir" },
	],
	kemahasiswaan: [
		{ name: "Rayyan Ridwan", prodi: "HI", semester: 5, img: "rayyan_ridwan" },
		{
			name: "Faturrahman Naufal",
			prodi: "TI",
			semester: 5,
			img: "faturrahman_naufal",
		},
		{ name: "Zufarul Haq", prodi: "K3", semester: 5, img: "zufarul_haq" },
		{ name: "Ilham Pribadi", prodi: "K3", semester: 5, img: "ilham_pribadi" },
		{ name: "Saddam Maulana", prodi: "HI", semester: 5, img: "saddam_maulana" },
		{ name: "Nurul Huda", prodi: "HI", semester: 5, img: "nurul_huda" },
		{ name: "Nur Hakim", prodi: "IQT", semester: 5, img: "nur_hakim" },
		{ name: "Azka Nasution", prodi: "PBA", semester: 5, img: "azka_nasution" },
		{ name: "Ahmada Shulton", prodi: "TI", semester: 5, img: "ahmada_shulton" },
		{ name: "Valdeze", prodi: "", semester: 3, img: "valdeze" },
	],
	perlengkapan: [
		{ name: "Fauzan", prodi: "IQT", semester: 5, img: "fauzan" },
		{ name: "Ilham Aqila", prodi: "IQT", semester: 5, img: "ilham_aqila" },
		{
			name: "Irwin Rizkillah",
			prodi: "PBA",
			semester: 5,
			img: "irwin_rizkillah",
		},
		{
			name: "Ahmad Musyawwir",
			prodi: "TIP",
			semester: 5,
			img: "ahmad_musyawwir",
		},
		{
			name: "Muhaimin Alfaqih",
			prodi: "K3",
			semester: 5,
			img: "muhaimin_alfaqih",
		},
		{ name: "Satya Adhi", prodi: "K3", semester: 5, img: "satya_adhi" },
		{ name: "Aditya Bagus", prodi: "TI", semester: 5, img: "aditya_bagus" },
		{ name: "Bayu Saputra", prodi: "TI", semester: 5, img: "bayu_saputra" },
		{ name: "Aidil Saputra", prodi: "IQT", semester: 5, img: "aidil_saputra" },
		{ name: "Ashim Hanif", prodi: "EI", semester: 5, img: "ashim_hanif" },
		{ name: "Syahan Syah", prodi: "TI", semester: 5, img: "syahan_syah" },
		{ name: "Wafa Al Faiz", prodi: "IQT", semester: 5, img: "wafa_al_faiz" },
		{ name: "Afif Aufarozi", prodi: "MNJ", semester: 5, img: "afif_aufarozi" },
		{
			name: "Fadhil Muhammad Hasan",
			prodi: "K3",
			semester: 5,
			img: "fadhil_muhammad",
		},
		{
			name: "Haidar Hilmi Habibi",
			prodi: "PAI",
			semester: 5,
			img: "haidar_hilmi",
		},
		{
			name: "Akbar Satyatama",
			prodi: "MNJ",
			semester: 3,
			img: "akbar_satyatama",
		},
		{ name: "Fatih Machael", prodi: "MNJ", semester: 3, img: "fatih_machael" },
	],
	konsumsi: [
		{ name: "Farrel El haq", prodi: "MNJ", semester: 5, img: "farrel_el_haq" },
		{
			name: "Lucky Fathul Adam",
			prodi: "K3",
			semester: 5,
			img: "lucky_fathul",
		},
		{ name: "Faysal Yahya", prodi: "PBA", semester: 5, img: "faysal_yahya" },
		{
			name: "Ramadan Chairul",
			prodi: "IQT",
			semester: 5,
			img: "ramadan_chairul",
		},
		{ name: "Afif Alhakim", prodi: "K3", semester: 5, img: "afif_alhakim" },
		{ name: "Adli Akmal", prodi: "EI", semester: 5, img: "adli_akmal" },
		{ name: "Fikri Rahmat", prodi: "K3", semester: 5, img: "fikri_rahmat" },
		{ name: "Lutfil Mulki", prodi: "PAI", semester: 5, img: "lutfil_mulki" },
	],
	bazzar: [
		{
			name: "Hibatullah Ramadahana",
			prodi: "MNJ",
			semester: 5,
			img: "hibatullah_ramadahana",
		},
		{ name: "Afkar Gilang", prodi: "AFI", semester: 5, img: "afkar_gilang" },
		{ name: "Tsalam Asytar", prodi: "PBA", semester: 5, img: "tsalam_asytar" },
		{
			name: "Labiq Alfahrozi",
			prodi: "AFI",
			semester: 5,
			img: "labiq_alfahrozi",
		},
		{
			name: "Galih Alfariski",
			prodi: "TI",
			semester: 5,
			img: "galih_alfariski",
		},
		{ name: "Malik Adnan", prodi: "HI", semester: 5, img: "malik_adnan" },
		{ name: "Ade Aula", prodi: "Ilkom", semester: 5, img: "ade_aula" },
		{ name: "Imam Ihsan", prodi: "HI", semester: 5, img: "imam_ihsan" },
		{ name: "Rafli Ikmal", prodi: "IQT", semester: 5, img: "rafli_ikmal" },
		{ name: "Alfin Susanto", prodi: "K3", semester: 5, img: "alfin_susanto" },
		{
			name: "Salman Albani",
			prodi: "Ilkom",
			semester: 5,
			img: "salman_albani",
		},
	],
	humas: [
		{ name: "Aqil Zafran", prodi: "HI", semester: 5, img: "aqil_zafran" },
		{ name: "Nungki Aji", prodi: "IQT", semester: 5, img: "nungki_aji" },
		{ name: "Hafiz Aqila", prodi: "PBA", semester: 5, img: "hafiz_aqila" },
		{ name: "Hanin Athaya", prodi: "MNJ", semester: 5, img: "hanin_athaya" },
		{ name: "Alfath Agel", prodi: "K3", semester: 5, img: "alfath_agel" },
		{ name: "Naufal Faiq", prodi: "IQT", semester: 5, img: "naufal_faiq" },
		{ name: "Riski Cahya", prodi: "PMH", semester: 5, img: "riski_cahya" },
		{ name: "Andra Alijza", prodi: "K3", semester: 5, img: "andra_alijza" },
		{ name: "Reza Alfarizi", prodi: "PAI", semester: 5, img: "reza_alfarizi" },
		{ name: "Zidhan Panji", prodi: "HI", semester: 3, img: "zidhan_panji" },
	],
	kesehatan: [
		{ name: "Wisnu Nasa", prodi: "K3", semester: 5, img: "wisnu_nasa" },
		{
			name: "Salman Alfarizi",
			prodi: "K3",
			semester: 5,
			img: "salman_alfarizi",
		},
		{ name: "Wafi Saif Azzam", prodi: "K3", semester: 5, img: "wafi_saif" },
		{ name: "Rafly Husein", prodi: "HI", semester: 5, img: "rafly_husein" },
	],
	keilmuan: [
		{
			name: "Reyhan Alfinata",
			prodi: "HI",
			semester: 5,
			img: "reyhan_alfinata",
		},
		{ name: "Fatih Khalil", prodi: "PBA", semester: 5, img: "fatih_khalil" },
		{
			name: "Raihan Firdaus",
			prodi: "IQT",
			semester: 5,
			img: "raihan_firdaus",
		},
		{ name: "Fahri Rabbani", prodi: "K3", semester: 5, img: "fahri_rabbani" },
		{ name: "Nabil Taqqiy", prodi: "K3", semester: 5, img: "nabil_taqqiy" },
		{ name: "Hendi Arya", prodi: "HI", semester: 5, img: "hendi_arya" },
	],
	penerimaan_mahasiswa_baru: [
		{
			name: "Dayyan Mannaungi",
			prodi: "K3",
			semester: 5,
			img: "dayyan_mannaungi",
		},
		{ name: "Naufal Azmi", prodi: "AGRO", semester: 5, img: "naufal_azmi" },
		{ name: "Fariq", prodi: "HI", semester: 5, img: "fariq" },
		{ name: "Mahis", prodi: "PBA", semester: 5, img: "mahis" },
		{ name: "Agus Gumelar", prodi: "PAI", semester: 5, img: "agus_gumelar" },
		{ name: "Nafis Ghozali", prodi: "PAI", semester: 5, img: "nafis_ghozali" },
		{ name: "Raka Fikriya", prodi: "MNJ", semester: 5, img: "raka_fikriya" },
		{ name: "Akhtar Sakha", prodi: "PBA", semester: 5, img: "akhtar_sakha" },
		{ name: "Azril", prodi: "HI", semester: 5, img: "azril" },
		{ name: "Syakir Rahman", prodi: "IQT", semester: 5, img: "syakir_rahman" },
		{
			name: "Dzikri Tiftajani",
			prodi: "AFI",
			semester: 5,
			img: "dzikri_tiftajani",
		},
		{ name: "Fajrul Hadi", prodi: "PAI", semester: 5, img: "fajrul_hadi" },
		{
			name: "Khalifah Rabbani",
			prodi: "HI",
			semester: 5,
			img: "khalifah_rabbani",
		},
		{
			name: "Aurel Raya Azalizidan",
			prodi: "MNJ",
			semester: 3,
			img: "aurel_raya",
		},
		{ name: "Azhad Salim", prodi: "TI", semester: 3, img: "azhad_salim" },
	],
	delegasi: [
		{ name: "Gaffa Akram", prodi: "IQT", semester: 5, img: "gaffa_akram" },
		{ name: "Umar Hanif", prodi: "IQT", semester: 3, img: "umar_hanif" },
		{
			name: "Risakngka Fikri",
			prodi: "AFI",
			semester: 5,
			img: "risakngka_fikri",
		},
		{ name: "Yusuf", prodi: "AFI", semester: 3, img: "yusuf" },
		{ name: "Zaki Alfahmi", prodi: "SAA", semester: 5, img: "zaki_alfahmi" },
		{ name: "Edo Kurniawan", prodi: "SAA", semester: 3, img: "edo_kurniawan" },
		{ name: "Firdaus", prodi: "PAI", semester: 5, img: "firdaus" },
		{ name: "Nandifa", prodi: "PAI", semester: 3, img: "nandifa" },
		{
			name: "Muhammad Iqbal",
			prodi: "PBA",
			semester: 5,
			img: "muhammad_iqbal",
		},
		{ name: "Doni Damara", prodi: "PBA", semester: 3, img: "doni_damara" },
		{ name: "Bima Arya", prodi: "TBI", semester: 5, img: "bima_arya" },
		{ name: "Makdisi Muda", prodi: "TBI", semester: 3, img: "makdisi_muda" },
		{ name: "Faisal Zaki", prodi: "PMH", semester: 5, img: "faisal_zaki" },
		{ name: "Moh Alvin Fawzie", prodi: "PMH", semester: 3, img: "moh_alvin" },
		{ name: "Firos Hasyim", prodi: "HES", semester: 5, img: "firos_hasyim" },
		{ name: "Revi Yuha Sya'bani", prodi: "HES", semester: 3, img: "revi_yuha" },
		{ name: "Abdul Mannar", prodi: "EI", semester: 5, img: "abdul_mannar" },
		{
			name: "Muhammad azka ramadhan",
			prodi: "EI",
			semester: 3,
			img: "muhammad_azka",
		},
		{
			name: "Deny Kurniawan",
			prodi: "MNJ",
			semester: 5,
			img: "deny_kurniawan",
		},
		{
			name: "Naufal Fernanda",
			prodi: "MNJ",
			semester: 3,
			img: "naufal_fernanda",
		},
		{ name: "Ariel Yusuf", prodi: "HI", semester: 5, img: "ariel_yusuf" },
		{
			name: "Mustofa Junisal",
			prodi: "HI",
			semester: 3,
			img: "mustofa_junisal",
		},
		{ name: "Haydar Afkar", prodi: "Ilkom", semester: 5, img: "haydar_afkar" },
		{ name: "Raja Najmul", prodi: "Ilkom", semester: 3, img: "raja_najmul" },
		{ name: "Farrel Ghozy", prodi: "TI", semester: 5, img: "farrel_ghozy" },
		{ name: "Dhiyau Kaukab", prodi: "TI", semester: 3, img: "dhiyau_kaukab" },
		{ name: "Reno Iswar", prodi: "AGRO", semester: 5, img: "reno_iswar" },
		{
			name: "Emir Fatuh Shamid",
			prodi: "AGRO",
			semester: 3,
			img: "emir_fatuh",
		},
		{ name: "Alif Al Akbar", prodi: "TIP", semester: 5, img: "alif_al_akbar" },
		{ name: "Naufal Faruq", prodi: "TIP", semester: 3, img: "naufal_faruq" },
		{ name: "Ulil Fahri", prodi: "K3", semester: 5, img: "ulil_fahri" },
		{ name: "Ridho Fajar", prodi: "K3", semester: 3, img: "ridho_fajar" },
		{ name: "Robby", prodi: "Kedokteran", semester: 5, img: "robby" },
		{
			name: "Aqil Ayashi",
			prodi: "Kedokteran",
			semester: 5,
			img: "aqil_ayashi",
		},
	],
	penanggung_jawab: [
		{
			name: "Muhammad Ikhram Sayid Alfath",
			prodi: "PMH",
			semester: 5,
			img: "muhammad_ikhram",
		},
		{ name: "Muhammad Faiq", prodi: "MNJ", semester: 5, img: "muhammad_faiq" },
	],
};
