interface Insides {
	name: string;
	prodi: string;
	semester: number;
	img?: string;
}

type Panitias = Record<string, Insides[]>;

export const panitias: Panitias = {
	ketua: [
		{
			name: "Muhammad Usama Hendra",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "usamahendra",
		},
		{
			name: "Satya Rizkiano",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "satya_rizkiano",
		},
		{
			name: "Fauzi Syahrul",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "fauzi_syahrul",
		},
	],
	sekretaris: [
		{
			name: "Abinaya Azhar Probo Kusumo",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "abinaya_azhar",
		},
		{
			name: "Wegig",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "wegig",
		},
		{
			name: "Jihad Khoiruddin",
			prodi: "Manajemen",
			semester: 5,
			img: "jihad_khoiruddin",
		},
		{
			name: "Zaki Kusnadi",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "zaki_kusnadi",
		},
		{
			name: "Akmal Fauzi",
			prodi: "Manajemen",
			semester: 5,
		},
	],
	bendahara: [
		{
			name: "Ridho Ilham",
			prodi: "Agroteknologi",
			semester: 5,
			img: "ridho_ilham",
		},
		{ name: "Aldhino", prodi: "Manajemen", semester: 5, img: "aldhino" },
		{ name: "Muhammad Rafie", prodi: "Manajemen", semester: 5, img: "rafie" },
		{
			name: "Salim Musyafa",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "salim_musyafa",
		},
	],
	keamanan: [
		{
			name: "Nazih Sukma",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "nazih_sukma",
		},
		{
			name: "Sidiq",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
		},
		{
			name: "Fauzan Hibaturrahman",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "fauzan_hibaturrahman",
		},
		{
			name: "Zaki Su'aidi",
			prodi: "Ekonomi Islam",
			semester: 5,
		},
		{
			name: "Ilham Ramadhan",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "ilham_ramadhan",
		},
		{
			name: "Arifa Bintang",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "arifa_bintang",
		},
		{
			name: "Firman Nurin",
			prodi: "Studi Agama-Agama",
			semester: 5,
			img: "firman_nurin",
		},
		{
			name: "Andhika Dzakwan",
			prodi: "Manajemen",
			semester: 5,
		},
		{
			name: "Nandhika",
			prodi: "Hubungan Internasional",
			semester: 5,
		},
		{
			name: "Ahmad Hanif",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "ahmad_hanif",
		},
		{
			name: "Naufal Dzaki",
			prodi: "Hubungan Internasional",
			semester: 5,
		},
		{
			name: "Dimitri Ulung",
			prodi: "Ekonomi Islam",
			semester: 5,
			img: "dimitri_ulung",
		},
		{
			name: "Shulthan Maulana Zuhdi",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "shulthan_maulana",
		},
		{
			name: "Brilliant Daffa",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
		},
		{
			name: "Aditya Al aziz",
			prodi: "Pendidikan Agama Islam",
			semester: 3,
		},
	],
	designer: [
		{
			name: "Rio Riyadi",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "rio_riyadi",
		},
		{
			name: "Samsu Yusa",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "samsu_yusa",
		},
		{
			name: "Edwin Fadhillah Putra",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "edwin_fadhillah",
		},
		{
			name: "Raffa Erfansyah",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "raffeerfansyah",
		},
		{
			name: "Haydar",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "haydar",
		},
		{
			name: "Alif Huda",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "alif_huda",
		},
		{
			name: "Sultan Al Kahfi",
			prodi: "Manajemen",
			semester: 5,
			img: "sultan_al_kahfi",
		},
		{
			name: "Brucad Almagribi",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "brucad_almagribi",
		},
		{
			name: "Mustaqim Nawahhudi",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "mustaqim_nawahudi",
		},
		{
			name: "Haedar Rafif Surya Negara",
			prodi: "Ilmu Komunikasi",
			semester: 3,
			img: "haedar_rafif",
		},
	],
	dokumentasi: [
		{
			name: "Dzil Izzat",
			prodi: "Tadris Bahasa Inggris",
			semester: 5,
			img: "dzil_izzat",
		},
		{
			name: "Aldhyto Hasan",
			prodi: "Manajemen",
			semester: 5,
			img: "aldhyto_hasan",
		},
		{
			name: "Aqila Zain",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "aqila_zain",
		},
		{
			name: "Amran Syarif",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "amran_syarif",
		},
		{
			name: "Najib Ramadhan",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "najib_ramadhan",
		},
		{
			name: "Almiftahul Riski",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "almiftahul_riski",
		},
		{
			name: "Althof Faizan",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "althof_faizan",
		},
		{
			name: "Reyhan Iskandar",
			prodi: "Teknik Informatika",
			semester: 3,
			img: "reyhan_iskandar",
		},
	],
	acara: [
		{
			name: "Arrayan Fikri",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "arrayan_fikri",
		},
		{
			name: "Muhammad Naufal",
			prodi: "Manajemen",
			semester: 5,
			img: "muhammad_naufal",
		},
		{
			name: "Dzaki Zidan",
			prodi: "Manajemen",
			semester: 5,
			img: "dzaki_zidan",
		},
		{
			name: "Fadhilmu'tasimbillah",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "fadhilmutasimbillah",
		},
		{ name: "Sun Fauzi", prodi: "Manajemen", semester: 5, img: "sun_fauzi" },
		{
			name: "Ahnaf Athaullah",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "ahnaf_athaullah",
		},
		{
			name: "Alfredo Rizky",
			prodi: "Manajemen",
			semester: 5,
			img: "alfredo_rizky",
		},
		{
			name: "Rafi Hanief",
			prodi: "Manajemen",
			semester: 5,
			img: "rafi_hanief",
		},
		{
			name: "Ghifari Alhafiz",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "ghifari_alhafiz",
		},
		{
			name: "Fauzi Hartanto",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "fauzi_hartanto",
		},
		{
			name: "Muhammad Rafi",
			prodi: "Manajemen",
			semester: 5,
			img: "muhammad_rafi",
		},
		{ name: "Halim", prodi: "Ilmu Komunikasi", semester: 3, img: "halim" },
	],
	kerohanian: [
		{
			name: "Taufiqnurrahman",
			prodi: "Manajemen",
			semester: 5,
			img: "taufiqnurrahman",
		},
		{
			name: "Taufiqie Anindia",
			prodi: "Manajemen",
			semester: 5,
			img: "taufiqie_anindia",
		},
		{
			name: "Muhammad Aditya Azka",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "muhammad_aditya",
		},
		{
			name: "Ghatan Alif",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "ghatan_alif",
		},
		{
			name: "Irfan Anshori",
			prodi: "Pendidikan Agama Islam",
			semester: 5,
			img: "irfan_anshori",
		},
		{
			name: "Kemal Mayitra",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "kemal_mayitra",
		},
		{
			name: "Azmi Rabbani",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "azmi_rabbani",
		},
		{
			name: "Hafiz Imron",
			prodi: "Hukum Ekonomi Syariah",
			semester: 5,
			img: "hafiz_imron",
		},
	],
	keolahragaan: [
		{
			name: "Riski Arrasyid",
			prodi: "Manajemen",
			semester: 5,
			img: "riski_arrasyid",
		},
		{
			name: "Agus Faisal",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "agus_faisal",
		},
		{
			name: "Zaki Fadhlurrahman",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "zaki_fadhlurrahman",
		},
		{
			name: "Hafizullah",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "hafizullah",
		},
		{
			name: "Ahmad Rafid Nuafal",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "ahmad_rafid",
		},
		{
			name: "Agung Abdullah",
			prodi: "Perbandingan Madzhab dan Hukum",
			semester: 5,
			img: "agung_abdullah",
		},
		{ name: "Ari Dwi", prodi: "Agroteknologi", semester: 5, img: "ari_dwi" },
		{
			name: "Keysfil Harir",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "keysfil_harir",
		},
	],
	kemahasiswaan: [
		{
			name: "Rayyan Ridwan",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "rayyan_ridwan",
		},
		{
			name: "Faturrahman Naufal",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "faturrahman_naufal",
		},
		{
			name: "Zufarul Haq",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "zufarul_haq",
		},
		{
			name: "Ilham Pribadi",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "ilham_pribadi",
		},
		{
			name: "Saddam Maulana",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "saddam_maulana",
		},
		{
			name: "Nurul Huda",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "nurul_huda",
		},
		{
			name: "Nur Hakim",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "nur_hakim",
		},
		{
			name: "Azka Nasution",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "azka_nasution",
		},
		{
			name: "Ahmada Shulton",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "ahmada_shulton",
		},
		{ name: "Valdeze", prodi: "", semester: 3, img: "valdeze" },
	],
	perlengkapan: [
		{
			name: "Fauzan",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "fauzan",
		},
		{
			name: "Ilham Aqila",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "ilham_aqila",
		},
		{
			name: "Irwin Rizkillah",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "irwin_rizkillah",
		},
		{
			name: "Ahmad Musyawwir",
			prodi: "Teknik Industri Pertanian",
			semester: 5,
			img: "ahmad_musyawwir",
		},
		{
			name: "Muhaimin Alfaqih",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "muhaimin_alfaqih",
		},
		{
			name: "Satya Adhi",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "satya_adhi",
		},
		{
			name: "Aditya Bagus",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "aditya_bagus",
		},
		{
			name: "Bayu Saputra",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "bayu_saputra",
		},
		{
			name: "Aidil Saputra",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "aidil_saputra",
		},
		{
			name: "Ashim Hanif",
			prodi: "Ekonomi Islam",
			semester: 5,
			img: "ashim_hanif",
		},
		{
			name: "Syahan Syah",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "syahan_syah",
		},
		{
			name: "Wafa Al Faiz",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "wafa_al_faiz",
		},
		{
			name: "Afif Aufarozi",
			prodi: "Manajemen",
			semester: 5,
			img: "afif_aufarozi",
		},
		{
			name: "Fadhil Muhammad Hasan",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "fadhil_muhammad",
		},
		{
			name: "Haidar Hilmi Habibi",
			prodi: "Pendidikan Agama Islam",
			semester: 5,
			img: "haidar_hilmi",
		},
		{
			name: "Akbar Satyatama",
			prodi: "Manajemen",
			semester: 3,
			img: "akbar_satyatama",
		},
		{
			name: "Fatih Machael",
			prodi: "Manajemen",
			semester: 3,
			img: "fatih_machael",
		},
	],
	konsumsi: [
		{
			name: "Farrel El haq",
			prodi: "Manajemen",
			semester: 5,
			img: "farrel_el_haq",
		},
		{
			name: "Lucky Fathul Adam",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "lucky_fathul",
		},
		{
			name: "Faysal Yahya",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "faysal_yahya",
		},
		{
			name: "Ramadan Chairul",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "ramadan_chairul",
		},
		{
			name: "Afif Alhakim",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "afif_alhakim",
		},
		{
			name: "Adli Akmal",
			prodi: "Ekonomi Islam",
			semester: 5,
			img: "adli_akmal",
		},
		{
			name: "Fikri Rahmat",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "fikri_rahmat",
		},
		{
			name: "Lutfil Mulki",
			prodi: "Pendidikan Agama Islam",
			semester: 5,
			img: "lutfil_mulki",
		},
	],
	bazzar: [
		{
			name: "Hibatullah Ramadahana",
			prodi: "Manajemen",
			semester: 5,
			img: "hibatullah_ramadahana",
		},
		{
			name: "Afkar Gilang",
			prodi: "Aqidah Filsafat Islam",
			semester: 5,
			img: "afkar_gilang",
		},
		{
			name: "Tsalam Asytar",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "tsalam_asytar",
		},
		{
			name: "Labiq Alfahrozi",
			prodi: "Aqidah Filsafat Islam",
			semester: 5,
			img: "labiq_alfahrozi",
		},
		{
			name: "Galih Alfariski",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "galih_alfariski",
		},
		{
			name: "Malik Adnan",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "malik_adnan",
		},
		{
			name: "Ade Aula",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "ade_aula",
		},
		{
			name: "Imam Ihsan",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "imam_ihsan",
		},
		{
			name: "Rafli Ikmal",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "rafli_ikmal",
		},
		{
			name: "Alfin Susanto",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "alfin_susanto",
		},
		{
			name: "Salman Albani",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "salman_albani",
		},
	],
	humas: [
		{
			name: "Aqil Zafran",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "aqil_zafran",
		},
		{
			name: "Nungki Aji",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "nungki_aji",
		},
		{
			name: "Hafiz Aqila",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "hafiz_aqila",
		},
		{
			name: "Hanin Athaya",
			prodi: "Manajemen",
			semester: 5,
			img: "hanin_athaya",
		},
		{
			name: "Alfath Agel",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "alfath_agel",
		},
		{
			name: "Naufal Faiq",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "naufal_faiq",
		},
		{
			name: "Riski Cahya",
			prodi: "Perbandingan Madzhab dan Hukum",
			semester: 5,
			img: "riski_cahya",
		},
		{
			name: "Andra Alijza",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "andra_alijza",
		},
		{
			name: "Reza Alfarizi",
			prodi: "Pendidikan Agama Islam",
			semester: 5,
			img: "reza_alfarizi",
		},
		{
			name: "Zidhan Panji",
			prodi: "Hubungan Internasional",
			semester: 3,
			img: "zidhan_panji",
		},
	],
	kesehatan: [
		{
			name: "Wisnu Nasa",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "wisnu_nasa",
		},
		{
			name: "Salman Alfarizi",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "salman_alfarizi",
		},
		{
			name: "Wafi Saif Azzam",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "wafi_saif",
		},
		{
			name: "Rafly Husein",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "rafly_husein",
		},
	],
	keilmuan: [
		{
			name: "Reyhan Alfinata",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "reyhan_alfinata",
		},
		{
			name: "Fatih Khalil",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "fatih_khalil",
		},
		{
			name: "Raihan Firdaus",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "raihan_firdaus",
		},
		{
			name: "Fahri Rabbani",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "fahri_rabbani",
		},
		{
			name: "Nabil Taqqiy",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "nabil_taqqiy",
		},
		{
			name: "Hendi Arya",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "hendi_arya",
		},
	],
	penerimaan_mahasiswa_baru: [
		{
			name: "Dayyan Mannaungi",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "dayyan_mannaungi",
		},
		{
			name: "Naufal Azmi",
			prodi: "Agroteknologi",
			semester: 5,
			img: "naufal_azmi",
		},
		{
			name: "Fariq",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "fariq",
		},
		{
			name: "Mahis",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "mahis",
		},
		{
			name: "Agus Gumelar",
			prodi: "Pendidikan Agama Islam",
			semester: 5,
			img: "agus_gumelar",
		},
		{
			name: "Nafis Ghozali",
			prodi: "Pendidikan Agama Islam",
			semester: 5,
			img: "nafis_ghozali",
		},
		{
			name: "Raka Fikriya",
			prodi: "Manajemen",
			semester: 5,
			img: "raka_fikriya",
		},
		{
			name: "Akhtar Sakha",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "akhtar_sakha",
		},
		{
			name: "Azril",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "azril",
		},
		{
			name: "Syakir Rahman",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "syakir_rahman",
		},
		{
			name: "Dzikri Tiftajani",
			prodi: "Aqidah Filsafat Islam",
			semester: 5,
			img: "dzikri_tiftajani",
		},
		{
			name: "Fajrul Hadi",
			prodi: "Pendidikan Agama Islam",
			semester: 5,
			img: "fajrul_hadi",
		},
		{
			name: "Khalifah Rabbani",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "khalifah_rabbani",
		},
		{
			name: "Aurel Raya Azalizidan",
			prodi: "Manajemen",
			semester: 3,
			img: "aurel_raya",
		},
		{
			name: "Azhad Salim",
			prodi: "Teknik Informatika",
			semester: 3,
			img: "azhad_salim",
		},
	],
	delegasi: [
		{
			name: "Gaffa Akram",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 5,
			img: "gaffa_akram",
		},
		{
			name: "Umar Hanif",
			prodi: "Ilmu Qur'an dan Tafsir",
			semester: 3,
			img: "umar_hanif",
		},
		{
			name: "Risakngka Fikri",
			prodi: "Aqidah Filsafat Islam",
			semester: 5,
			img: "risakngka_fikri",
		},
		{
			name: "Yusuf",
			prodi: "Aqidah Filsafat Islam",
			semester: 3,
			img: "yusuf",
		},
		{
			name: "Zaki Alfahmi",
			prodi: "Studi Agama-Agama",
			semester: 5,
			img: "zaki_alfahmi",
		},
		{
			name: "Edo Kurniawan",
			prodi: "Studi Agama-Agama",
			semester: 3,
			img: "edo_kurniawan",
		},
		{
			name: "Firdaus",
			prodi: "Pendidikan Agama Islam",
			semester: 5,
			img: "firdaus",
		},
		{
			name: "Nandifa",
			prodi: "Pendidikan Agama Islam",
			semester: 3,
			img: "nandifa",
		},
		{
			name: "Muhammad Iqbal",
			prodi: "Pendidikan Bahasa Arab",
			semester: 5,
			img: "muhammad_iqbal",
		},
		{
			name: "Doni Damara",
			prodi: "Pendidikan Bahasa Arab",
			semester: 3,
			img: "doni_damara",
		},
		{
			name: "Bima Arya",
			prodi: "Tadris Bahasa Inggris",
			semester: 5,
			img: "bima_arya",
		},
		{
			name: "Makdisi Muda",
			prodi: "Tadris Bahasa Inggris",
			semester: 3,
			img: "makdisi_muda",
		},
		{
			name: "Faisal Zaki",
			prodi: "Perbandingan Madzhab dan Hukum",
			semester: 5,
			img: "faisal_zaki",
		},
		{
			name: "Moh Alvin Fawzie",
			prodi: "Perbandingan Madzhab dan Hukum",
			semester: 3,
			img: "moh_alvin",
		},
		{
			name: "Firos Hasyim",
			prodi: "Hukum Ekonomi Syariah",
			semester: 5,
			img: "firos_hasyim",
		},
		{
			name: "Revi Yuha Sya'bani",
			prodi: "Hukum Ekonomi Syariah",
			semester: 3,
			img: "revi_yuha",
		},
		{
			name: "Abdul Mannar",
			prodi: "Ekonomi Islam",
			semester: 5,
			img: "abdul_mannar",
		},
		{
			name: "Muhammad azka ramadhan",
			prodi: "Ekonomi Islam",
			semester: 3,
			img: "muhammad_azka",
		},
		{
			name: "Deny Kurniawan",
			prodi: "Manajemen",
			semester: 5,
			img: "deny_kurniawan",
		},
		{
			name: "Naufal Fernanda",
			prodi: "Manajemen",
			semester: 3,
			img: "naufal_fernanda",
		},
		{
			name: "Ariel Yusuf",
			prodi: "Hubungan Internasional",
			semester: 5,
			img: "ariel_yusuf",
		},
		{
			name: "Mustofa Junisal",
			prodi: "Hubungan Internasional",
			semester: 3,
			img: "mustofa_junisal",
		},
		{
			name: "Haydar Afkar",
			prodi: "Ilmu Komunikasi",
			semester: 5,
			img: "haydar_afkar",
		},
		{
			name: "Raja Najmul",
			prodi: "Ilmu Komunikasi",
			semester: 3,
			img: "raja_najmul",
		},
		{
			name: "Farrel Ghozy",
			prodi: "Teknik Informatika",
			semester: 5,
			img: "farrel_ghozy",
		},
		{
			name: "Dhiyau Kaukab",
			prodi: "Teknik Informatika",
			semester: 3,
			img: "dhiyau_kaukab",
		},
		{
			name: "Reno Iswar",
			prodi: "Agroteknologi",
			semester: 5,
			img: "reno_iswar",
		},
		{
			name: "Emir Fatuh Shamid",
			prodi: "Agroteknologi",
			semester: 3,
			img: "emir_fatuh",
		},
		{
			name: "Alif Al Akbar",
			prodi: "Teknik Industri Pertanian",
			semester: 5,
			img: "alif_al_akbar",
		},
		{
			name: "Naufal Faruq",
			prodi: "Teknik Industri Pertanian",
			semester: 3,
			img: "naufal_faruq",
		},
		{
			name: "Ulil Fahri",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 5,
			img: "ulil_fahri",
		},
		{
			name: "Ridho Fajar",
			prodi: "Keselamatan & Kesehatan Kerja",
			semester: 3,
			img: "ridho_fajar",
		},
		{ name: "Robby", prodi: "Kedokteran", semester: 5, img: "robby" },
		{
			name: "Aqil Ayashi",
			prodi: "Kedokteran",
			semester: 5,
			img: "aqil_ayashi",
		},
	],
	penanggung_jawab: [
		{
			name: "Muhammad Ikhram Sayid Alfath",
			prodi: "Perbandingan Madzhab dan Hukum",
			semester: 5,
			img: "muhammad_ikhram",
		},
		{
			name: "Muhammad Faiq",
			prodi: "Manajemen",
			semester: 5,
			img: "muhammad_faiq",
		},
	],
};
